version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    environment:
      NODE_ENV: development
    command: npm run dev
